# Generated by Django 3.0.5 on 2020-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20200627_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_client',
            name='placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipping_client',
            name='shipping_status',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
