# Generated by Django 3.0.5 on 2020-06-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_shipping_client_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_client',
        ),
    ]
