# Generated by Django 3.0.5 on 2020-06-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200625_2350'),
        ('Cart', '0005_auto_20200626_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.ProductDetails'),
        ),
    ]
