# Generated by Django 3.0.5 on 2020-06-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_delete_shipping_client'),
        ('Cart', '0008_shipping_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_client',
            name='user',
        ),
        migrations.AddField(
            model_name='shipping_client',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Profile'),
        ),
    ]
