# Generated by Django 3.0.5 on 2020-06-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Brand')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Categories')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='model',
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('warranty', models.TextField()),
                ('function', models.CharField(max_length=100)),
                ('dial_color', models.CharField(max_length=10)),
                ('case_shape', models.CharField(max_length=10)),
                ('case_material', models.CharField(max_length=50)),
                ('case_thickness', models.FloatField()),
                ('case_length', models.FloatField()),
                ('case_width', models.FloatField()),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Collection')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.Products')),
            ],
        ),
    ]
